import type { ReactNode } from "react";

/** Tailwind utilities scoped to the reader; no document-wide style leakage on navigation. */
export default function BookReaderLayout({ children }: { children: ReactNode }) {
  return (
    <div className="[&_.select-item_.n]:font-mono [&_.toc-part_.n]:font-mono [&_.pg_figcaption]:font-mono min-h-screen
      isolate
      relative
      [background:#111a30]
      [color:#f6f8fd]
      overflow-x-hidden
      [&::before]:[content:'']
      [&::before]:fixed
      [&::before]:inset-0
      [&::before]:[z-index:-1]
      [&::before]:pointer-events-none
      [&::before]:[background:radial-gradient(50rem_34rem_at_88%_-6%,rgb(56_189_248/.16),transparent_62%),_radial-gradient(46rem_32rem_at_8%_2%,rgb(139_92_246/.16),transparent_64%),_linear-gradient(180deg,#0e1729,#111a30_40%,#16203c_100%)]
      [&_a]:text-inherit
      [&_.sr]:absolute
      [&_.sr]:[width:1px]
      [&_.sr]:[height:1px]
      [&_.sr]:overflow-hidden
      [&_.sr]:[clip:rect(0_0_0_0)]
      [&_.sr]:whitespace-nowrap
      [&_.skip]:fixed
      [&_.skip]:[top:.7rem]
      [&_.skip]:[inset-inline-start:1rem]
      [&_.skip]:[z-index:200]
      [&_.skip]:[transform:translateY(-8rem)]
      [&_.skip]:[padding:.55rem_.85rem]
      [&_.skip]:[border-radius:.6rem]
      [&_.skip]:font-extrabold
      [&_.skip]:no-underline
      [&_.skip]:[background:rgb(56_189_248)]
      [&_.skip]:[color:#03101a]
      [&_.skip:focus]:[transform:none]
      [&_:focus-visible]:[outline:3px_solid_rgb(56_189_248)]
      [&_:focus-visible]:[outline-offset:3px]
      [&_:focus-visible]:[border-radius:8px]
      [&_.bar]:sticky
      [&_.bar]:top-0
      [&_.bar]:[z-index:90]
      [&_.bar]:[background:rgba(17,26,48,.86)]
      [&_.bar]:[backdrop-filter:blur(16px)_saturate(140%)]
      [&_.bar]:[border-bottom:1px_solid_hsla(0,0%,100%,.08)]
      [&_.bar-in]:flex
      [&_.bar-in]:items-center
      [&_.bar-in]:[gap:12px]
      [&_.bar-in]:[min-height:60px]
      [&_.bar-in]:[width:min(1180px,calc(100%_-_28px))]
      [&_.bar-in]:mx-auto
      [&_.home]:inline-flex
      [&_.home]:items-center
      [&_.home]:[gap:6px]
      [&_.home]:shrink-0
      [&_.home]:no-underline
      [&_.home]:[font-size:13px]
      [&_.home]:font-bold
      [&_.home]:[color:#b2bcd0]
      [&_.home]:[padding:8px_10px]
      [&_.home]:[border-radius:10px]
      [&_.home]:[border:1px_solid_hsla(0,0%,100%,.14)]
      [&_.home]:[background:rgba(32,43,72,.6)]
      [&_.home]:[transition:color_.16s,border-color_.16s]
      [&_.home:hover]:text-white
      [&_.home:hover]:[border-color:rgb(56_189_248/.5)]
      [&_.home_svg]:[width:16px]
      [&_.home_svg]:[height:16px]
      [&_.ident]:grid
      [&_.ident]:[line-height:1.3]
      [&_.ident]:min-w-0
      [&_.ident]:[margin-inline-end:auto]
      [&_.ident_strong]:[font-size:14px]
      [&_.ident_strong]:font-extrabold
      [&_.ident_strong]:whitespace-nowrap
      [&_.ident_strong]:overflow-hidden
      [&_.ident_strong]:text-ellipsis
      [&_.ident_span]:[font-size:11.5px]
      [&_.ident_span]:[color:#8b95ad]
      [&_.tools]:flex
      [&_.tools]:items-center
      [&_.tools]:[gap:8px]
      [&_.tools]:shrink-0
      [&_.select]:relative
      [&_.select-trigger]:inline-flex
      [&_.select-trigger]:items-center
      [&_.select-trigger]:[gap:8px]
      [&_.select-trigger]:[min-height:38px]
      [&_.select-trigger]:[padding:8px_12px]
      [&_.select-trigger]:[font-size:12.5px]
      [&_.select-trigger]:font-bold
      [&_.select-trigger]:[color:#b2bcd0]
      [&_.select-trigger]:cursor-pointer
      [&_.select-trigger]:[background:rgba(32,43,72,.7)]
      [&_.select-trigger]:[border:1px_solid_hsla(0,0%,100%,.14)]
      [&_.select-trigger]:[border-radius:10px]
      [&_.select-trigger]:[transition:color_.16s,border-color_.16s]
      [&_.select-trigger:hover]:text-white
      [&_.select-trigger:hover]:[border-color:rgb(56_189_248/.55)]
      [&_.select-trigger[aria-expanded='true']]:text-white
      [&_.select-trigger[aria-expanded='true']]:[border-color:rgb(56_189_248/.75)]
      [&_.select-value]:[max-width:200px]
      [&_.select-value]:overflow-hidden
      [&_.select-value]:text-ellipsis
      [&_.select-value]:whitespace-nowrap
      [&_.select-value.ph]:[color:#8b95ad]
      [&_.select-value.ph]:font-semibold
      [&_.select-chevron]:[width:15px]
      [&_.select-chevron]:[height:15px]
      [&_.select-chevron]:shrink-0
      [&_.select-chevron]:[opacity:.75]
      [&_.select-chevron]:[transition:transform_.18s]
      [&_.select-trigger[aria-expanded='true']_.select-chevron]:[transform:rotate(180deg)]
      [&_.select-pop]:absolute
      [&_.select-pop]:[top:calc(100%_+_8px)]
      [&_.select-pop]:[inset-inline-end:0]
      [&_.select-pop]:[z-index:120]
      [&_.select-pop]:[width:min(370px,88vw)]
      [&_.select-pop]:[max-height:min(64vh,500px)]
      [&_.select-pop]:overflow-y-auto
      [&_.select-pop]:overscroll-contain
      [&_.select-pop]:[padding:6px]
      [&_.select-pop]:[border:1px_solid_hsla(0,0%,100%,.14)]
      [&_.select-pop]:[border-radius:14px]
      [&_.select-pop]:[background:#182240]
      [&_.select-pop]:[box-shadow:0_26px_64px_rgba(0,0,0,.5)]
      [&_.select-pop]:animate-reader-pop
      [&_.select-pop[hidden]]:hidden
      [&_.select-pop::-webkit-scrollbar]:[width:8px]
      [&_.select-pop::-webkit-scrollbar-thumb]:[background:hsla(0,0%,100%,.14)]
      [&_.select-pop::-webkit-scrollbar-thumb]:[border-radius:8px]
      [&_.select-label]:[padding:9px_10px_4px]
      [&_.select-label]:[font-size:11px]
      [&_.select-label]:font-extrabold
      [&_.select-label]:[letter-spacing:.03em]
      [&_.select-label]:[color:rgb(56_189_248)]
      [&_.select-item]:grid
      [&_.select-item]:[grid-template-columns:auto_1fr_auto]
      [&_.select-item]:items-center
      [&_.select-item]:[gap:9px]
      [&_.select-item]:[padding:8px_10px]
      [&_.select-item]:[border-radius:9px]
      [&_.select-item]:cursor-pointer
      [&_.select-item]:[font-size:13px]
      [&_.select-item]:font-semibold
      [&_.select-item]:[color:#b2bcd0]
      [&_.select-item_.n]:[font-size:10.5px]
      [&_.select-item_.n]:font-bold
      [&_.select-item_.n]:[color:rgb(56_189_248)]
      [&_.select-item_.t]:min-w-0
      [&_.select-item_.t]:overflow-hidden
      [&_.select-item_.t]:text-ellipsis
      [&_.select-item_.t]:whitespace-nowrap
      [&_.select-item_.check]:[width:15px]
      [&_.select-item_.check]:[height:15px]
      [&_.select-item_.check]:invisible
      [&_.select-item_.check]:[color:rgb(56_189_248)]
      [&_.select-item.hl]:[background:hsla(0,0%,100%,.07)]
      [&_.select-item.hl]:text-white
      [&_.select-item[aria-selected='true']]:text-white
      [&_.select-item[aria-selected='true']_.check]:visible
      [&_.icon]:grid
      [&_.icon]:place-items-center
      [&_.icon]:[width:38px]
      [&_.icon]:[height:38px]
      [&_.icon]:[border-radius:10px]
      [&_.icon]:cursor-pointer
      [&_.icon]:[border:1px_solid_hsla(0,0%,100%,.14)]
      [&_.icon]:[background:rgba(32,43,72,.7)]
      [&_.icon]:[color:#f6f8fd]
      [&_.icon_svg]:[width:19px]
      [&_.icon_svg]:[height:19px]
      [&_.icon:hover]:[border-color:rgb(56_189_248/.5)]
      [&_.dl]:inline-flex
      [&_.dl]:items-center
      [&_.dl]:[gap:6px]
      [&_.dl]:no-underline
      [&_.dl]:[font-size:12.5px]
      [&_.dl]:font-extrabold
      [&_.dl]:[padding:9px_13px]
      [&_.dl]:[border-radius:10px]
      [&_.dl]:[color:#03101a]
      [&_.dl]:[background:linear-gradient(135deg,rgb(56_189_248),color-mix(in_srgb,rgb(56_189_248)_70%,rgb(139_92_246)))]
      [&_.dl]:[box-shadow:0_10px_26px_rgb(56_189_248/.22)]
      [&_.dl_svg]:[width:16px]
      [&_.dl_svg]:[height:16px]
      [&_.progress]:[height:2px]
      [&_.progress]:[background:transparent]
      [&_.progress_i]:block
      [&_.progress_i]:h-full
      [&_.progress_i]:[width:0]
      [&_.progress_i]:[background:rgb(56_189_248)]
      [&_.progress_i]:[transition:width_.12s_linear]
      max-[761px]:[&_.ident_span]:hidden
      max-[761px]:[&_.select]:hidden
      max-[761px]:[&_.home_span]:hidden
      max-[761px]:[&_.home]:[padding:9px]
      [&_.scrim]:fixed
      [&_.scrim]:inset-0
      [&_.scrim]:[z-index:95]
      [&_.scrim]:[background:rgba(6,10,22,.6)]
      [&_.scrim]:[backdrop-filter:blur(3px)]
      [&_.scrim]:animate-reader-fade
      [&_.toc]:fixed
      [&_.toc]:[z-index:96]
      [&_.toc]:[inset-block:0]
      [&_.toc]:[inset-inline-end:0]
      [&_.toc]:[width:min(430px,90vw)]
      [&_.toc]:flex
      [&_.toc]:flex-col
      [&_.toc]:[background:#182240]
      [&_.toc]:[border-inline-start:1px_solid_hsla(0,0%,100%,.14)]
      [&_.toc]:[box-shadow:-30px_0_70px_rgba(0,0,0,.42)]
      [&_.toc]:animate-reader-slide
      [&_.toc[hidden]]:hidden
      [&_.scrim[hidden]]:hidden
      [&_.toc-top]:flex
      [&_.toc-top]:items-center
      [&_.toc-top]:justify-between
      [&_.toc-top]:[gap:10px]
      [&_.toc-top]:[padding:16px_18px]
      [&_.toc-top]:[border-bottom:1px_solid_hsla(0,0%,100%,.08)]
      [&_.toc-top_strong]:[font-size:15px]
      [&_.toc-top_strong]:font-extrabold
      [&_.toc-body]:overflow-y-auto
      [&_.toc-body]:[padding:8px_12px_22px]
      [&_.toc-body]:overscroll-contain
      [&_.toc-part]:[margin-top:14px]
      [&_.toc-part_h3]:[margin:0_0_8px]
      [&_.toc-part_h3]:[padding:0_6px]
      [&_.toc-part_h3]:[font-size:11.5px]
      [&_.toc-part_h3]:font-extrabold
      [&_.toc-part_h3]:[letter-spacing:.04em]
      [&_.toc-part_h3]:[color:rgb(56_189_248)]
      [&_.toc-part_ol]:list-none
      [&_.toc-part_ol]:[margin:0]
      [&_.toc-part_ol]:[padding:0]
      [&_.toc-part_ol]:grid
      [&_.toc-part_ol]:[gap:2px]
      [&_.toc-part_a]:grid
      [&_.toc-part_a]:[grid-template-columns:auto_1fr_auto]
      [&_.toc-part_a]:items-center
      [&_.toc-part_a]:[gap:10px]
      [&_.toc-part_a]:[padding:9px_10px]
      [&_.toc-part_a]:[border-radius:10px]
      [&_.toc-part_a]:no-underline
      [&_.toc-part_a]:[transition:background_.14s]
      [&_.toc-part_a:hover]:[background:hsla(0,0%,100%,.06)]
      [&_.toc-part_a.on]:[background:rgb(56_189_248/.14)]
      [&_.toc-part_.n]:[font-size:11px]
      [&_.toc-part_.n]:font-bold
      [&_.toc-part_.n]:[color:rgb(56_189_248)]
      [&_.toc-part_.n]:[min-width:20px]
      [&_.toc-part_.t]:grid
      [&_.toc-part_.t]:[line-height:1.45]
      [&_.toc-part_.t]:min-w-0
      [&_.toc-part_.t]:[font-size:13.5px]
      [&_.toc-part_.t]:font-bold
      [&_.toc-part_.t_em]:not-italic
      [&_.toc-part_.t_em]:[font-size:11.5px]
      [&_.toc-part_.t_em]:font-medium
      [&_.toc-part_.t_em]:[color:#8b95ad]
      [&_.toc-part_.t_em]:overflow-hidden
      [&_.toc-part_.t_em]:text-ellipsis
      [&_.toc-part_.t_em]:whitespace-nowrap
      [&_.toc-part_.p]:[font-size:10.5px]
      [&_.toc-part_.p]:[color:#8b95ad]
      [&_.toc-part_.p]:whitespace-nowrap
      [&_.pages]:[width:min(820px,calc(100%_-_24px))]
      [&_.pages]:[margin:26px_auto_0]
      [&_.pages]:grid
      [&_.pages]:[gap:16px]
      [&_.pages]:[overflow-anchor:none]
      [&_.ch-head]:[margin:26px_0_6px]
      [&_.ch-head]:[padding:18px_20px]
      [&_.ch-head]:[border-radius:16px]
      [&_.ch-head]:[border:1px_solid_hsla(0,0%,100%,.14)]
      [&_.ch-head]:[background:linear-gradient(145deg,rgba(32,43,72,.9),rgba(24,34,60,.72))]
      [&_.ch-head]:[scroll-margin-top:0]
      [&_.ch-head_.kicker]:block
      [&_.ch-head_.kicker]:[font-size:11px]
      [&_.ch-head_.kicker]:font-extrabold
      [&_.ch-head_.kicker]:[letter-spacing:.05em]
      [&_.ch-head_.kicker]:[color:rgb(56_189_248)]
      [&_.ch-head_.kicker]:[margin-bottom:6px]
      [&_.ch-head_h2]:[margin:0]
      [&_.ch-head_h2]:[font-size:clamp(18px,2.6vw,23px)]
      [&_.ch-head_h2]:font-extrabold
      [&_.ch-head_h2]:[line-height:1.4]
      [&_.ch-head_p]:[margin:6px_0_0]
      [&_.ch-head_p]:[font-size:13.5px]
      [&_.ch-head_p]:[color:#b2bcd0]
      [&_.ch-head_p]:[line-height:1.6]
      [&_.pg]:[margin:0]
      [&_.pg]:relative
      [&_.pg_img]:block
      [&_.pg_img]:w-full
      [&_.pg_img]:h-auto
      [&_.pg_img]:[border-radius:12px]
      [&_.pg_img]:[border:1px_solid_hsla(0,0%,100%,.08)]
      [&_.pg_img]:bg-white
      [&_.pg_img]:[box-shadow:0_14px_40px_rgba(0,0,0,.3)]
      [&_.pg_figcaption]:absolute
      [&_.pg_figcaption]:[inset-block-end:9px]
      [&_.pg_figcaption]:[inset-inline-start:9px]
      [&_.pg_figcaption]:[font-size:10px]
      [&_.pg_figcaption]:font-bold
      [&_.pg_figcaption]:[padding:3px_7px]
      [&_.pg_figcaption]:[border-radius:6px]
      [&_.pg_figcaption]:[color:#b2bcd0]
      [&_.pg_figcaption]:[background:rgba(17,26,48,.8)]
      [&_.pg_figcaption]:[backdrop-filter:blur(4px)]
      [&_.end]:[width:min(820px,calc(100%_-_24px))]
      [&_.end]:[margin:34px_auto_0]
      [&_.end]:[padding:26px_0_40px]
      [&_.end]:[border-top:1px_solid_hsla(0,0%,100%,.08)]
      [&_.end]:text-center
      [&_.end_p]:[margin:0_0_14px]
      [&_.end_p]:[font-size:14px]
      [&_.end_p]:font-bold
      [&_.end-cta]:flex
      [&_.end-cta]:flex-wrap
      [&_.end-cta]:[gap:9px]
      [&_.end-cta]:justify-center
      [&_.btn]:inline-flex
      [&_.btn]:items-center
      [&_.btn]:justify-center
      [&_.btn]:[min-height:42px]
      [&_.btn]:[padding:9px_16px]
      [&_.btn]:[border-radius:11px]
      [&_.btn]:no-underline
      [&_.btn]:[font-size:13px]
      [&_.btn]:font-extrabold
      [&_.btn]:[border:1px_solid_hsla(0,0%,100%,.14)]
      [&_.btn]:[background:rgba(32,43,72,.7)]
      [&_.btn]:[color:#f6f8fd]
      [&_.btn.primary]:[border-color:transparent]
      [&_.btn.primary]:[color:#03101a]
      [&_.btn.primary]:[background:linear-gradient(135deg,rgb(56_189_248),color-mix(in_srgb,rgb(56_189_248)_70%,rgb(139_92_246)))]
      [&_.end_small]:block
      [&_.end_small]:[margin-top:16px]
      [&_.end_small]:[font-size:11.5px]
      [&_.end_small]:[color:#8b95ad]
      [&_.to-top]:fixed
      [&_.to-top]:[inset-block-end:18px]
      [&_.to-top]:[inset-inline-start:18px]
      [&_.to-top]:[z-index:80]
      [&_.to-top]:grid
      [&_.to-top]:place-items-center
      [&_.to-top]:[width:44px]
      [&_.to-top]:[height:44px]
      [&_.to-top]:rounded-full
      [&_.to-top]:cursor-pointer
      [&_.to-top]:[border:1px_solid_hsla(0,0%,100%,.14)]
      [&_.to-top]:[background:rgba(24,34,60,.9)]
      [&_.to-top]:[color:#f6f8fd]
      [&_.to-top]:[backdrop-filter:blur(8px)]
      [&_.to-top]:[box-shadow:0_10px_28px_rgba(0,0,0,.35)]
      [&_.to-top[hidden]]:hidden
      [&_.to-top_svg]:[width:20px]
      [&_.to-top_svg]:[height:20px]
      motion-reduce:[&_.toc]:[animation:none]
      motion-reduce:[&_.scrim]:[animation:none]">
      {children}
    </div>
  );
}
